const users = [
    {
        name: 'Admin User',
        email: 'admin@example.com',
        password: 'password123',
        isAdmin: true,
    },
    {
        name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
    },
    {
        name: 'Jane Doe',
        email: 'jane@example.com',
        password: 'password123',
    },
];

const products = [
    {
        name: 'Air Jordan 1 Retro High',
        image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=2012&ixlib=rb-4.0.3',
        description:
            'The Air Jordan 1 Retro High Remastered Series organizes the 30th anniversary of the Air Jordan franchise.',
        brand: 'Nike',
        category: 'Men',
        price: 180.0,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        name: 'Ultraboost Light Running Shoes',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3',
        description:
            'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever.',
        brand: 'Adidas',
        category: 'Sports',
        price: 190.0,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
    },
    {
        name: 'Chuck Taylor All Star',
        image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3',
        description:
            'The unmistakable Chuck Taylor All Star Classic celebrates the iconic high top silhouette.',
        brand: 'Converse',
        category: 'Casual',
        price: 60.0,
        countInStock: 0,
        rating: 4.8,
        numReviews: 15,
    },
    {
        name: 'Puma Suede Classic',
        image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3',
        description:
            'The Suede hit the scene in 1968 and has been changing the game ever since.',
        brand: 'Puma',
        category: 'Casual',
        price: 70.0,
        countInStock: 15,
        rating: 4.1,
        numReviews: 5,
    },
    {
        name: 'Nike Air Max 90',
        image: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3',
        description:
            'The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole.',
        brand: 'Nike',
        category: 'Women',
        price: 130.0,
        countInStock: 5,
        rating: 4.6,
        numReviews: 10,
    },
    {
        name: 'Vans Old Skool',
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=1998&ixlib=rb-4.0.3',
        description:
            'The Old Skool was our first footwear design to showcase the famous Vans Sidestripe.',
        brand: 'Vans',
        category: 'Kids',
        price: 65.0,
        countInStock: 12,
        rating: 4.7,
        numReviews: 20,
    },
    {
        name: 'Adidas Stan Smith Sustainability',
        image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aef4?auto=format&fit=crop&q=80&w=1931&ixlib=rb-4.0.3',
        description: 'A timeless classic, reborn. The Stan Smith shoes are the essence of cool, clean style.',
        brand: 'Adidas',
        category: 'Casual',
        price: 100.0,
        countInStock: 20,
        rating: 4.3,
        numReviews: 25,
    },
    {
        name: 'Timberland Premium 6-Inch Boot',
        image: 'https://images.unsplash.com/photo-1579338559194-a162d19bd842?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3',
        description: 'The original yellow boot that started it all. Waterproof and recognizable worldwide.',
        brand: 'Timberland',
        category: 'Boots',
        price: 198.0,
        countInStock: 8,
        rating: 4.9,
        numReviews: 40,
    },
    {
        name: 'New Balance 574 Core',
        image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=2012&ixlib=rb-4.0.3',
        description: 'The MOST New Balance shoe ever. Unassumingly, arguably, and likely the best.',
        brand: 'New Balance',
        category: 'Sports',
        price: 85.0,
        countInStock: 15,
        rating: 4.5,
        numReviews: 18,
    },
    {
        name: 'Dr. Martens 1460 Smooth Leather',
        image: 'https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?auto=format&fit=crop&q=80&w=2080&ixlib=rb-4.0.3',
        description: 'The connection between self-expression and Dr. Martens is unbreakable.',
        brand: 'Dr. Martens',
        category: 'Boots',
        price: 170.0,
        countInStock: 6,
        rating: 4.7,
        numReviews: 32,
    },
    {
        name: 'Italian Leather Oxford',
        image: 'https://images.unsplash.com/photo-1478146896981-b80c463e7e22?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3',
        description: 'Handcrafted Italian leather oxfords for the modern gentleman.',
        brand: 'Magnanni',
        category: 'Formal',
        price: 350.0,
        countInStock: 4,
        rating: 5.0,
        numReviews: 3,
    },
    {
        name: 'Yeezy Boost 350 V2',
        image: 'https://images.unsplash.com/photo-1634913745672-132d0045239e?auto=format&fit=crop&q=80&w=2070&ixlib=rb-4.0.3',
        description: 'Cutting-edge sneaker culture icon. Innovative design meets premium comfort.',
        brand: 'Adidas',
        category: 'Limited',
        price: 230.0,
        countInStock: 2,
        rating: 4.8,
        numReviews: 150,
    },
    {
        name: 'Reebok Club C 85 Vintage',
        image: 'https://images.unsplash.com/photo-1584735175315-9d5df23860e6?auto=format&fit=crop&q=80&w=1887&ixlib=rb-4.0.3',
        description: 'Clean, minimalist design that works with everything in your closet.',
        brand: 'Reebok',
        category: 'Casual',
        price: 90.0,
        countInStock: 18,
        rating: 4.4,
        numReviews: 10,
    },
    {
        name: 'Salomon XT-6 Advanced',
        image: 'https://images.unsplash.com/photo-1695646875865-c99c95e1e704?auto=format&fit=crop&q=80&w=1932&ixlib=rb-4.0.3',
        description: 'A world-class trail shoe that has found its way to the city streets.',
        brand: 'Salomon',
        category: 'Hiking',
        price: 200.0,
        countInStock: 10,
        rating: 4.9,
        numReviews: 22,
    },
];

module.exports = { users, products };
